### ISSUE TITLE
启动springboot-example项目redis无法连接

### ISSUE THREAD

**Issue by YIXIANG0234** [Redick01/lightweight-rate-limiter#9]
1.想启动springboot-example项目，报错redis连接不上，application.yml配置文件相关配置如下：
spring:
  ratelimiter:
    redis-config:
      url: 127.0.0.1
      database: 11
      password: root
2.经检查，密码没有错误，本地使用的redis版本是7.2的，报错信息如下，该如何解决？
Caused by: io.lettuce.core.RedisCommandExecutionException: NOAUTH HELLO must be called with the client already authenticated, otherwise the HELLO <proto> AUTH <user> <pass> option can be used to authenticate the client and select the RESP protocol version at the same time
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:137) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
	at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:110) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
	at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
	at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.72.Final.jar:4.1.72.Final]
	... 1 common frames omitted

**Comment by Redick01** [comment]
> 1.想启动springboot-example项目，报错redis连接不上，application.yml配置文件相关配置如下： spring: ratelimiter: redis-config: url: 127.0.0.1 database: 11 password: root 2.经检查，密码没有错误，本地使用的redis版本是7.2的，报错信息如下，该如何解决？ Caused by: io.lettuce.core.RedisCommandExecutionException: NOAUTH HELLO must be called with the client already authenticated, otherwise the HELLO AUTH option can be used to authenticate the client and select the RESP protocol version at the same time at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:137) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE] at io.lettuce.core.internal.ExceptionFactory.createExecutionException(ExceptionFactory.java:110) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE] at io.lettuce.core.protocol.AsyncCommand.completeResult(AsyncCommand.java:120) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE] at io.lettuce.core.protocol.AsyncCommand.complete(AsyncCommand.java:111) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE] at io.lettuce.core.protocol.CommandWrapper.complete(CommandWrapper.java:63) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE] at io.lettuce.core.protocol.CommandHandler.complete(CommandHandler.java:746) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE] at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:681) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE] at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:598) ~[lettuce-core-6.1.5.RELEASE.jar:6.1.5.RELEASE] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.72.Final.jar:4.1.72.Final] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.72.Final.jar:4.1.72.Final] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.72.Final.jar:4.1.72.Final] at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.72.Final.jar:4.1.72.Final] ... 1 common frames omitted

请问您那边redis是Sentinel模式吗

**Comment by YIXIANG0234** [comment]
单机模式，debug了下，其实就是建立连接到时候password字段弄丢了，密码没传下去，LettuceConnectionFactory类中的delegate对象里面没有密码，但是不知道咋修改

**Comment by Redick01** [comment]
> 单机模式，debug了下，其实就是建立连接到时候password字段弄丢了，密码没传下去，LettuceConnectionFactory类中的delegate对象里面没有密码，但是不知道咋修改
那我用你的redis版本调试下

**Comment by YIXIANG0234** [comment]
> > 单机模式，debug了下，其实就是建立连接到时候password字段弄丢了，密码没传下去，LettuceConnectionFactory类中的delegate对象里面没有密码，但是不知道咋修改
> > 那我用你的redis版本调试下

redis版本7.2.1

**Comment by Redick01** [comment]
> > > 单机模式，debug了下，其实就是建立连接到时候password字段弄丢了，密码没传下去，LettuceConnectionFactory类中的delegate对象里面没有密码，但是不知道咋修改
> > > 那我用你的redis版本调试下
> 
> redis版本7.2.1

我什么都没改，docker安装的 7.2.1版本，启动无问题，

**Comment by Redick01** [comment]
> > > > 单机模式，debug了下，其实就是建立连接到时候password字段弄丢了，密码没传下去，LettuceConnectionFactory类中的delegate对象里面没有密码，但是不知道咋修改
> > > > 那我用你的redis版本调试下
> > 
> > 
> > redis版本7.2.1
> 
> 我什么都没改，docker安装的 7.2.1版本，启动无问题，

我搞定了，你装redis是后将 requirepass设置成""这样的空字符串就可以了

**Comment by Redick01** [comment]
> requirepass

还有就是application.yml中的password 对应的应该是 redis的 requirepass

**Comment by Redick01** [comment]
> > > 单机模式，debug了下，其实就是建立连接到时候password字段弄丢了，密码没传下去，LettuceConnectionFactory类中的delegate对象里面没有密码，但是不知道咋修改
> > > 那我用你的redis版本调试下
> 
> redis版本7.2.1

我push了新代码

**Comment by YIXIANG0234** [comment]
> > > > > 单机模式，debug了下，其实就是建立连接到时候password字段弄丢了，密码没传下去，LettuceConnectionFactory类中的delegate对象里面没有密码，但是不知道咋修改
> > > > > 那我用你的redis版本调试下
> > > 
> > > 
> > > redis版本7.2.1
> > 
> > 
> > 我什么都没改，docker安装的 7.2.1版本，启动无问题，
> 
> 我搞定了，你装redis是后将 requirepass设置成""这样的空字符串就可以了

你的意思是redis不要设置密码吗？但是我的redis就是设置了密码的，application.yml中的password就是填的设置的redis密码，我用anotherRedisDesktopManager能正常连接的，现在的问题是说项目连接不上设置了密码的redis实例吧？

**Comment by Redick01** [comment]
> > > > > > 单机模式，debug了下，其实就是建立连接到时候password字段弄丢了，密码没传下去，LettuceConnectionFactory类中的delegate对象里面没有密码，但是不知道咋修改
> > > > > > 那我用你的redis版本调试下
> > > > 
> > > > 
> > > > redis版本7.2.1
> > > 
> > > 
> > > 我什么都没改，docker安装的 7.2.1版本，启动无问题，
> > 
> > 
> > 我搞定了，你装redis是后将 requirepass设置成""这样的空字符串就可以了
> 
> 你的意思是redis不要设置密码吗？但是我的redis就是设置了密码的，application.yml中的password就是填的设置的redis密码，我用anotherRedisDesktopManager能正常连接的，现在的问题是说项目连接不上设置了密码的redis实例吧？

也不是不设置，yml中配置的密码应该和 redis的requirepass一致的，而不是password
